version: "3.9"
services:
  nessus:
    image: "ciromota/nessus-scanner:latest"
#    build: .
    ports:
      - "8834:8834"
    volumes:
       - /etc/localtime:/etc/localtime
    restart: on-failure   